/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogItem: typeof import('./src/components/BlogItem.vue')['default']
    CategoryItem: typeof import('./src/components/CategoryItem.vue')['default']
    CategoryItem4List: typeof import('./src/components/CategoryItem4List.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTree: typeof import('element-plus/es')['ElTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserItem: typeof import('./src/components/UserItem.vue')['default']
    UserItem4List: typeof import('./src/components/UserItem4List.vue')['default']
  }
}
